name: EAS Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build Android app with EAS
        run: npx eas-cli@latest build --platform android --profile preview --non-interactive --no-wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}